# -*- coding: utf-8 -*-
"""SEMANA 07 T1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NeAtL9Htmzd85H7ctJMwzbDssuMizvi

Escreva um programa que leia um número inteiro entre 10 e 99, mostre uma das mensagens, a seguir, conforme o
número lido.
• Nenhum dígito é ímpar.
• Apenas um dígito é ímpar.
• Os dois dígitos são ímpares.
"""

def num(x):
  u = x%10
  d = (x%100)//10
  if u%2 == 1 and d%2 == 1:
    return 'Os dois dígitos são ímpares.'
  
  elif u%2 == 1 or d%2 == 1:
    return 'Apenas um dígito é ímpar.'
  
  else:
    return 'Nenhum dígito é ímpar.'

yy = int(input())

ch1 = num(yy)

print(ch1)