# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPLVbXM5n5aOE_OL9qT6oWSHpb-YV22G

Escreva um programa que leia um número inteiro entre 100 e 999, mostre quantos dígitos pares existem nesse
número. Por exemplo: 245 tem 2 dígitos pares; 135 tem 0 dígitos pares; 134 tem 1 dígito par.
"""

def num(x):
  qtd_par = 0
  u = x % 10
  d = (x % 100) // 10
  c = x // 100
  if u % 2 == 0:
    qtd_par += 1
  if c > 0 and d % 2 == 0:
    qtd_par += 1
  if c % 2 == 0 and c != 0:
    qtd_par += 1 
  return qtd_par

n = int(input())

ch = num(n)


print(ch)