# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPLVbXM5n5aOE_OL9qT6oWSHpb-YV22G
"""

def pes(nome):
    dividir_juntar = ''.join(nome.split())
    contar = len(dividir_juntar)
    return contar

def est(estado_civil):
    if '1' in estado_civil:
      conjuge = input()
      dividir_juntar_2 = ''.join(conjuge.split())
      contar_2 = len(dividir_juntar_2)
      return contar_2
    else:
      return 0

nome_pessoa = input()
casado_solteiro = input()

ch1 = pes(nome_pessoa)
ch2 = est(casado_solteiro)

print(ch1 + ch2)

"""Escreva um programa que leia o nome e o estado civil de uma pessoa, considere apenas “1” para casado e “2” para
solteiro. Se a pessoa for casada, leia, também, o nome do cônjuge. Mostre quantos caracteres no total existem no(s)
nome(s) lido(s).
"""