# -*- coding: utf-8 -*-
"""SEMANA 07 T1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NeAtL9Htmzd85H7ctJMwzbDssuMizvi

Escreva um programa que leia a data de nascimento do usuário, e informa qual o seu signo. Considere exatamente:
Áries (21/03 a 19/04); Touro (20/04 a 20/05); Gêmeos (21/05 a 21/06); Câncer (22/06 a 22/07); Leão (23/07 a
22/08); Virgem (23/08 a 22/09); Libra (23/09 a 22/10); Escorpião (23/10 a 21/11); Sagitário (22/11 a 21/12);
Capricórnio (22/12 a 19/01); Aquário (20/01 a 18/02); Peixes (19/02 a 20/03);
"""

def signo(d, m):
  if m == 3:
    if d >= 21:
      return 'Áries'
    else:
      return 'Peixes'
  
  elif m == 4:
    if d >= 20:
      return 'Touro'
    else:
      return 'Áries'
    
  elif m == 5:
    if d >= 21:
      return 'Gêmeos'
    else:
      return 'Touro'
  
  elif m == 6:
    if d >= 22:
      return 'Câncer'
    else:
      return 'Gêmeos'

  elif m == 7:
    if d >= 23:
      return 'Leão'
    else:
      return 'Câncer'

  elif m == 8:
    if d >= 23:
      return 'Virgem'
    else:
      return 'Leão'

  elif m == 9:
    if d >= 23:
      return 'Libra'
    else:
      return 'Virgem'
    
  elif m == 10:
    if d >= 23:
      return 'Escorpião'
    else:
      return 'Libra'
  
  elif m == 11:
    if d >= 22:
      return 'Sagitário'
    else:
      return 'Escorpião'

  elif m == 12:
    if d >= 22:
      return 'Capricórnio'
    else:
      return 'Sagitário'

  elif m == 1:
    if d >= 20:
      return 'Aquário'
    else:
      return 'Capricórnio'

  elif m == 2:
    if d >= 19:
      return 'Peixes'
    else:
      return 'Aquário'
  
  elif m == 3:
    if d >= 21:
      return 'Áries'
    else:
      return 'Peixes'

dia = int(input())
mes = int(input())

ch1 = signo(dia, mes)

print(ch1)